name: Deploy Lambda Code

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-2
      IMAGE_UPLOADER_DEV: image-uploader-dev
      IMAGE_UPLOADER_PROD: image-uploader-prod
      S3_EVENT_LOGGER_DEV: s3-event-logger-dev
      S3_EVENT_LOGGER_PROD: s3-event-logger-prod  # same for prod, change if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select AWS credentials
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> $GITHUB_ENV
            echo "IMAGE_UPLOADER_FN=${{ env.IMAGE_UPLOADER_DEV }}" >> $GITHUB_ENV
            echo "EVENT_LOGGER_FN=${{ env.S3_EVENT_LOGGER_DEV }}" >> $GITHUB_ENV
          else
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
            echo "IMAGE_UPLOADER_FN=${{ env.IMAGE_UPLOADER_PROD }}" >> $GITHUB_ENV
            echo "EVENT_LOGGER_FN=${{ env.S3_EVENT_LOGGER_PROD }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip uploader Lambda
        run: |
          cd lambda/upload_handler
          zip -r ../../upload_handler.zip .
          cd ../..

      - name: Zip event logger Lambda
        run: |
          cd lambda/event_logger
          zip -r ../../event_logger.zip .
          cd ../..

      - name: Zip list_uploads Lambda
        run: |
          cd lambda/list_uploads
          zip -r ../../list_uploads.zip .
          cd ../..

      - name: Deploy uploader Lambda
        run: |
          aws lambda update-function-code \
            --function-name "$IMAGE_UPLOADER_FN" \
            --zip-file fileb://upload_handler.zip

      - name: Deploy event logger Lambda
        run: |
          aws lambda update-function-code \
            --function-name "$EVENT_LOGGER_FN" \
            --zip-file fileb://event_logger.zip
      
      - name: Deploy list_uploads Lambda
        run: |
          aws lambda update-function-code \
            --function-name "$LIST_UPLOADS_FN" \
            --zip-file fileb://list_uploads.zip
      
